version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: hdd_fixer_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: hdd_fixer
      POSTGRES_PASSWORD: hdd_fixer_secret
      POSTGRES_DB: hdd_fixer_db
    ports:
      - '5436:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U hdd_fixer -d hdd_fixer_db' ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: hdd_fixer_redis
    restart: unless-stopped
    ports:
      - '6380:6379'
    volumes:
      - redisdata:/data
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  redisdata:
