import type { ComponentType } from 'react';
import { Database, HardDrive, IdCard, Server, Usb } from 'lucide-react';

export const EQUIPMENT_ICONS: Record<string, ComponentType<any>> = {
  hdd: HardDrive,
  'hdd drive': HardDrive,
  'hard drive': HardDrive,
  'жесткий диск': HardDrive,
  'жёсткий диск': HardDrive,
  'винчестер': HardDrive,
  диск: HardDrive,
  ssd: Database,
  'ssd drive': Database,
  твердотельный: Database,
  'твердотельный накопитель': Database,
  накопитель: Database,
  'm.2': Database,
  nvme: Database,
  external: HardDrive,
  внешний: HardDrive,
  переносной: HardDrive,
  portable: HardDrive,
  raid: Database,
  массив: Database,
  'raid массив': Database,
  server: Server,
  сервер: Server,
  серверное: Server,
  nas: Server,
  хранилище: Server,
  'система хранения': Server,
  схран: Server,
  usb: Usb,
  флешка: Usb,
  флеш: Usb,
  flash: Usb,
  'usb flash': Usb,
  'memory card': IdCard,
  'карта памяти': IdCard,
  карта: IdCard,
  'sd card': IdCard,
  sd: IdCard,
  microsd: IdCard,
  'micro sd': IdCard,
  compactflash: IdCard,
  'cf card': IdCard,
  disc: Database,
  'диск cd': Database,
  'диск dvd': Database,
  cd: Database,
  dvd: Database,
  bluray: Database,
  'blue ray': Database,
  computer: Database,
  компьютер: Database,
  пк: Database,
  'пк компьютер': Database,
  desktop: Database,
  ноутбук: Database,
  laptop: Database,
  default: HardDrive,
};

export const DEFAULT_EQUIPMENTS = [
  { id: '1', name_rus: 'Жёсткий диск HDD', name_eng: 'Hard Drive HDD' },
  { id: '2', name_rus: 'SSD накопитель', name_eng: 'SSD Drive' },
  { id: '3', name_rus: 'Внешний диск', name_eng: 'External Drive' },
  { id: '4', name_rus: 'USB флешка', name_eng: 'USB Flash' },
  { id: '5', name_rus: 'Карта памяти SD', name_eng: 'SD Card' },
  { id: '6', name_rus: 'Карта microSD', name_eng: 'microSD Card' },
  { id: '7', name_rus: 'RAID массив', name_eng: 'RAID Array' },
  { id: '8', name_rus: 'Сервер NAS', name_eng: 'NAS Server' },
  { id: '9', name_rus: 'Компьютер', name_eng: 'Computer' },
  { id: '10', name_rus: 'Ноутбук', name_eng: 'Laptop' },
];

export const DEFAULT_ISSUES = [
  { id: '1', name_rus: 'Не определяется', name_eng: 'Not detected' },
  { id: '2', name_rus: 'Определяется но не читается', name_eng: 'Detected but not readable' },
  { id: '3', name_rus: 'Посторонние звуки (щелчки)', name_eng: 'Strange sounds (clicking)' },
  { id: '4', name_rus: 'Потеря данных', name_eng: 'Data loss' },
  { id: '5', name_rus: 'Файлы повреждены', name_eng: 'Files corrupted' },
  { id: '6', name_rus: 'Случайное форматирование', name_eng: 'Accidental format' },
  { id: '7', name_rus: 'Удаление файлов', name_eng: 'Deleted files' },
  { id: '8', name_rus: 'Падение или удар', name_eng: 'Drop or impact' },
  { id: '9', name_rus: 'Попадание жидкости', name_eng: 'Liquid damage' },
  { id: '10', name_rus: 'Скачок напряжения', name_eng: 'Power surge' },
  { id: '11', name_rus: 'Сгорела плата', name_eng: 'Burnt PCB' },
  { id: '12', name_rus: 'Не раскручивается диск', name_eng: 'Disk not spinning' },
  { id: '13', name_rus: 'Ошибки чтения', name_eng: 'Read errors' },
  { id: '14', name_rus: 'Тормозит и зависает', name_eng: 'Slow and freezing' },
  { id: '15', name_rus: 'Пропадает из системы', name_eng: 'Disappears from system' },
  { id: '16', name_rus: 'Другая проблема', name_eng: 'Other issue' },
];
